name: Main

on:
  push:
    tags:
      - "v*.*.*"
jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 9.0.x
        - name: Restore tools
          run: dotnet workload restore
        - name: Restore dependencies
          run: dotnet restore


        - name: Build
          shell: bash
          run: |
            tag=$(git describe --tags --abbrev=0)
            release_name="PkFrontier-$tag-${{ matrix.target }}"
  
            # Build everything
            dotnet publish PkFactory.Desktop/PkFactory.Desktop.csproj /property:DebugType=None /property:DebugSymbols=false --runtime "${{ matrix.target }}" -c Release -o "$release_name"
  
            # Pack files
            if [ "${{ matrix.target }}" == "win-x64" ]; then
              # Pack to zip for Windows
              7z a -tzip "${release_name}.zip" "./${release_name}/*"
            else
            tar czvf "${release_name}.tar.gz" "$release_name"
            fi
  
            # Delete output directory
            rm -r "$release_name"
  
        - name: Publish
          uses: softprops/action-gh-release@v2
          with:
            files: |
              PkFrontier* 
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}